export const FETCH_SEARCH_HOT = 'fetchSearchHot'
export const FETCH_QUESTION_HOT = 'fetchQuestionHot'
export const FETCH_QUESTION_BY_TAG = 'fetchQuestionByTag'
export const FETCH_TAG_HOT = 'fetchTagHot'
export const FETCH_QUESTION_NEW = 'fetchQuestionNew'