export const FETCH_SEARCH_HOT = 'fetchSearchHot'
export const FETCH_QUESTION_HOT = 'fetchQuestionHot'
export const FETCH_QUESTION_BY_TAG = 'fetchQuestionByTag'
export const FETCH_TAG_HOT = 'fetchTagHot'
export const FETCH_QUESTION_NEW = 'fetchQuestionNew'
export const FETCH_QUESTION_BY_SEARCH = 'fetchQuestionBySearch'
export const FETCH_PROFILE_IDENTITY = 'fetchProfileIdentity'
export const FETCH_ONE_QUESTION_BY_ID = 'fetchOneQuestionById'
