export const FETCH_START = 'fetchStart'
export const FETCH_END = 'fetchEnd'
export const SET_SEARCH_HOT = 'setSearchHot'
export const SET_QUESTION_HOT = 'setQuestionHot'
export const SET_QUESTION_NEW = 'setQuestionNew'
export const SET_TAG_HOT = 'setTagHot'