export const FETCH_START = 'fetchStart'
export const FETCH_END = 'fetchEnd'
export const SET_SEARCH_HOT = 'setSearchHot'
export const SET_QUESTION_LIST = 'setQuestionList'
export const SET_TAG_HOT = 'setTagHot'
export const SET_PROFILE_IDENTITY = 'serProfileIdentity'
export const SET_ONE_QUESTION = 'setOneQuestion'
export const SET_QUESTION_SOLVE = 'setQuestionSolve'
export const SET_MORE_QUESTION = 'setMoreQuestion'

export const SET_ANSWER_APPROVAL = 'setAnswerApproval' 
export const SET_ANSWER_OPPOSE = 'setAnswerOppose'

export const SET_PROFILE_ANSWER = 'setProfileAnswer'
export const SET_PROFILE_APPROVAL = 'setProfileApproval'
export const SET_PROFILE_OPPOSE = 'setProfileOppose'

export const SET_EDIT_WORDS = 'setEditWords'
export const SET_EDIT_TAGS = 'setEditTags'
export const SET_EDIT_IMAGES = 'setEditImages'
export const DELETE_EDIT_IMAGES = 'deleteEditImages'
export const DELETE_EDIT_TAGS = 'deleteEditTags'

export const DELETE_QUESTION = 'deleteQuestion'
export const DELETE_ANSWER = 'deleteAnswer'