export const FETCH_START = 'setLoading'
export const SET_SEARCH_HOT = 'setSearchHot'
export const SET_QUESTION_HOT = 'setQuestionHot'
export const SET_QUESTION_NEW = 'setQuestionNew'
export const SET_TAG_HOT = 'setTagHot'